### ISSUE TITLE
Volume for plugins, scripts and backups

### ISSUE THREAD

**Issue by nanuit** [QuantumObject/docker-domoticz#4]
Is there a way to define volumes for the 
scripts
backups and
plugins folders 
within domoticz to access them from outside docker?

**Comment by angelrr7702** [comment]
Location inside of container appear to be : 

/domoticz/scripts
/domoticz/plugins

-v <LOCAL DIRECTORY PATH>:/domoticz/plugins

You will be able to access the container too by docker exec -it container_id /bin/bash

sincerely
Angel Rodriguez

**Comment by angelrr7702** [comment]
done with volume for this container  :   
    /domoticz/scripts
   /domoticz/plugins

rebuilding docker build 

please let me know of any problem 

sincerely
Angel Rodriguez
